// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfOhiZ2pWImYyY8Bo1q28WbaXHVuH5Lw',
    appId: '1:915161575957:web:1d70c6d43b98a6d3e2141c',
    messagingSenderId: '915161575957',
    projectId: 'netflix-clone-test2-10ff4',
    authDomain: 'netflix-clone-test2-10ff4.firebaseapp.com',
    storageBucket: 'netflix-clone-test2-10ff4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwXLki57BJ6Fr_QLhAFM7lVBZFvUBo6I',
    appId: '1:915161575957:android:78d028a8d19da80be2141c',
    messagingSenderId: '915161575957',
    projectId: 'netflix-clone-test2-10ff4',
    storageBucket: 'netflix-clone-test2-10ff4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpoZd2zE8oU_0HTePZbKM0fWURGJ4L0Q',
    appId: '1:915161575957:ios:b1f551d7e9027a0ce2141c',
    messagingSenderId: '915161575957',
    projectId: 'netflix-clone-test2-10ff4',
    storageBucket: 'netflix-clone-test2-10ff4.appspot.com',
    iosClientId: '915161575957-rht4fdjhfvdvd3nrnkdp8rqq826k2ldq.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixUiClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpoZd2zE8oU_0HTePZbKM0fWURGJ4L0Q',
    appId: '1:915161575957:ios:b1f551d7e9027a0ce2141c',
    messagingSenderId: '915161575957',
    projectId: 'netflix-clone-test2-10ff4',
    storageBucket: 'netflix-clone-test2-10ff4.appspot.com',
    iosClientId: '915161575957-rht4fdjhfvdvd3nrnkdp8rqq826k2ldq.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixUiClone',
  );
}
